FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["ApiGateway.csproj", "./"]

RUN dotnet restore "ApiGateway.csproj"

COPY . .

# Build in Debug configuration
RUN dotnet build "ApiGateway.csproj" -c Debug -o /app/build
#RUN dotnet build "ApiGateway.csproj" -c Release -o /app/build

FROM build AS publish

# Publish in Debug configuration
RUN dotnet publish "ApiGateway.csproj" -c Debug -o /app/publish
# RUN dotnet publish "ApiGateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "ApiGateway.dll"]
